image,imageTag,imageDigest,platform,hasFix,cve,cveReferences,cveDescription,highestSeverity,vulnerableVersions,fixedVersions,cvePublished,cveLastModified,artifactNames,artifactTypes,artifactPaths,severities,cvssBaseScores,highestCvssBaseScore,cvssExploitabilityScores,highestCvssExploitabilityScore,cvssImpactScores,highestCvssImpactScore,cvssVectors,exploitDBRefs,vulnerableBuildSteps,vulnerableLayerNumbers,baseLayerVulnerability,notes,scannerHits,tags
"ibm-maas360-apps-dev-app-management","10.91-DEV-20240702.101835","sha256:f2619372c2786bd9eafd833a99982791a784c8df7c280c25fb3b44599dbb76eb","linux:amd64:","Yes","CVE-2023-45803","https://nvd.nist.gov/vuln/detail/CVE-2023-45803 - twistlock","urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn\\'t remove the HTTP request body when an HTTP redirect response using status 301\, 302\, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects\, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally\, many users aren\\'t putting sensitive data in HTTP request bodies\, if this is the case then this vulnerability isn\\'t exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301\, 302\, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable red","medium","1.24.2","2.0.7","2023-10-17",,"urllib3","python","/usr/lib/python3.6/site-packages/urllib3-1.24.2-py3.6.egg-info","medium - twistlock","4.2 - twistlock","4.2",,,,,"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",,"22","0","true",,"twistlock","nvd-status(undergoing analysis)"
